FROM  centos
MAINTAINER youdi<liangchangyoujackson@gmail.com>

ENV MYPATH /usr/local

RUN yum  -y install vim
RUN yum -y install net-tools

EXPOSE 80


CMD echo $MYPATH
CMD echo "successful------ok------"
CMD /bin/bash
